name: Continuous Integration

on:
  push:
    branches:
      - "**"

jobs:
  Maven_Build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check Node.js version
        run: node --version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        run: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            mkdir -p $HOME/android-sdk/cmdline-tools
            cd $HOME/android-sdk
            wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
            unzip commandlinetools-linux-*.zip -d cmdline-tools
            mv cmdline-tools/cmdline-tools cmdline-tools/tools
            export PATH=$PATH:$HOME/android-sdk/cmdline-tools/tools/bin
            yes | sdkmanager --licenses
            sdkmanager "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"    

      - name: Setup appium
        run: |
          npm install -g appium@2.12.0
          appium driver install uiautomator2
          appium driver list --installed
          appium -v
          appium &>/dev/null &    

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 5
          script: |
            adb wait-for-device
            adb shell getprop sys.boot_completed

      - name: Restart ADB
        run: |
          adb kill-server
          adb start-server
          adb devices

      - name: List Connected Devices
        run: adb devices

      - name: Build project with Maven
        run: mvn test -DsuiteXmlFiles=testngTamimi.xml -DappName=Tamimi

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: Extent Report
          path: reports/ExtentReport.html

