name: Continuous Integration

on:
  push:
    branches: 
      - "**"

jobs:
  Maven_Build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Node.js version
        run: node --version

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: setup appium
        run: |
            npm install -g appium@2.12.0
            appium -v
            appium &>/dev/null &

      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 30
            arch: x86_64  # Changed to x86_64

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

      - name: Build project with Maven
        run: mvn test -DsuiteXmlFiles=testngTamimi.xml -DappName=Tamimi
